[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "https://www.nodegy.com/api/*"
  to = "https://www.nodegy-api.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"